#!/usr/bin/with-contenv bash

cat <<EOF
---
qbit-matUI Theme Installer
Source: https://github.com/bill-ahmed/qbit-matUI
---
EOF

LATEST_RELEASE=$(curl -s -L https://api.github.com/repos/bill-ahmed/qbit-matUI/releases/latest |
  grep "browser_download_url.*Unix.*zip" |
  cut -d : -f 2,3 |
  tr -d \" |
  xargs) # to trim whitespace

if [ ! -d /qbit-matui ]; then
  echo "Running installer..."

  curl -o qbit-matui.zip -L $LATEST_RELEASE &&
    unzip qbit-matui.zip -d /

  # Remove zip after unpacking
  rm /qbit-matui.zip

  echo "Done! The theme is installed in the root folder. Apply it from WEBUI settings."
else
  echo "qbit-matUI theme is already installed. Exiting..."
fi
